config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "New restaurant created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to @restaurant, notice: "Review added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1 class="mx-auto p-4" style="width: 600px">Liste des restaurants</h1>

<ul class="list-group grid gap-3 mx-4">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item list-group-item-secondary mx-4">
      <%= link_to restaurant.name, restaurant_path(restaurant), class: "fw-bolder p-3 mb-2 bg-info-subtle text-info-emphasis text-decoration-none" %>
    </li>
  <% end %>
</ul>

<div class="mx-auto p-2" style="width: 200px;">
  <%= link_to "Add a restaurant", new_restaurant_path, class: "btn btn-primary" %>
</div>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :phone_number, label: "Phone Number" %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], label: "Category", prompt: "Select a category" %>

  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

<%= link_to "Return", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Address :</strong> <%= @restaurant.address %></p>
<p><strong>Phone_number :</strong> <%= @restaurant.phone_number %></p>
<p><strong>Category :</strong> <%= @restaurant.category %></p>

<h2>Review :</h2>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <strong>Rating :</strong> <%= review.rating %> - <%= review.content %>
    </li>
  <% end %>
</ul>

<div class="d-grid gap-2 col-2">
  <%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to "Return to list", restaurants_path, class: "btn btn-primary" %>
</div>

app/views/reviews/new.html.erb
<h1>Add a review <%= @restaurant.name %></h1>

<%= form_with model: [@restaurant, @review], local: true do |form| %>
  <p>
    <%= form.label :content, "Your review" %>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :rating, "Note (0 à 5)" %>
    <%= form.number_field :rating, in: 0..5 %>
  </p>

  <%= form.submit "Add review" %>
<% end %>

<%= link_to "Return", restaurant_path(@restaurant) %>